export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";


export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_POST = "PRODUCT_POST";


export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const GET_TO_CART_SUCCESS = 'GET_TO_CART_SUCCESS'
export const DELETE_TO_CART_SUCCESS = 'DELETE_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE'